name: Build Smart Installers

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-installers:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Build smart installers
      run: |
        cd installer
        python build_installers.py

    - name: List generated files
      run: |
        echo "Generated installer files:"
        ls -la installer/dist/
        echo ""
        echo "File sizes:"
        du -h installer/dist/*

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: smart-installers
        path: installer/dist/*

  create-release:
    needs: build-installers
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        name: smart-installers
        path: ./release-assets

    - name: List release assets
      run: |
        echo "Release assets:"
        ls -la ./release-assets/
        echo ""
        echo "File sizes and checksums:"
        cd ./release-assets
        for file in *; do
          if [ -f "$file" ]; then
            size=$(du -h "$file" | cut -f1)
            sha256=$(sha256sum "$file" | cut -d' ' -f1)
            echo "📦 $file ($size) - SHA256: $sha256"
          fi
        done

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: ./release-assets/*
        body: |
          # 🚀 HLS Downloader ${{ github.ref_name }} - Ultra-Simplified Smart Installers
          
          ## 🎉 MAJOR SIMPLIFICATION
          
          We've **dramatically simplified** the installation process! Instead of 9+ files, you now get just **2 smart installers** that do everything automatically.
          
          ### 📦 Available Installers
          
          #### 🪟 Windows
          - **File**: `HLS-Downloader-Smart-Installer-Windows.bat` (~5KB)
          - **Installation**: Simply double-click the `.bat` file
          - **Requirements**: Windows 7+ with PowerShell
          
          #### 🍎 macOS & 🐧 Linux  
          - **File**: `HLS-Downloader-Smart-Installer-Unix.sh` (~10KB)
          - **Installation**: 
            ```bash
            chmod +x HLS-Downloader-Smart-Installer-Unix.sh
            ./HLS-Downloader-Smart-Installer-Unix.sh
            ```
          - **Requirements**: macOS 10.12+ or Linux with bash
          
          ## ✨ What Each Installer Does Automatically
          
          1. **Downloads** portable Python (no system changes needed!)
          2. **Downloads** latest HLS Downloader source code
          3. **Installs** all dependencies automatically  
          4. **Downloads** Playwright browsers
          5. **Builds** the final application
          6. **Creates** desktop shortcuts/app bundles
          7. **Cleans up** all temporary files
          8. **Leaves** only the app and browsers (~200MB total)
          
          ## 🎯 Key Benefits
          
          - **Tiny Downloads**: 5-10KB installers vs 800MB+ bundled apps
          - **Always Latest**: Downloads the newest version automatically
          - **No Python Required**: Installs portable Python automatically
          - **One-Click Setup**: Everything happens automatically
          - **Self-Contained**: Final result includes everything needed
          - **Cross-Platform**: Smart OS detection and setup
          
          ## 📍 Installation Locations
          
          - **Windows**: `%USERPROFILE%\HLS-Downloader\`
          - **macOS**: `~/Applications/HLS-Downloader/` + App Bundle
          - **Linux**: `~/.local/share/HLS-Downloader/` + Desktop Entry
          
          ## 🆘 Troubleshooting
          
          If installation fails:
          1. Check internet connection
          2. Ensure write permissions to installation directory
          3. On Linux: Install `curl`, `wget`, and `unzip` if missing
          4. On macOS: Install Xcode Command Line Tools if needed
          
          ---
          
          **Total download during installation**: ~50-80MB  
          **Final app size**: ~200MB (includes everything)  
          **Installation time**: 2-5 minutes (depending on internet speed)
          
          🎉 **This is the cleanest, most efficient way to install HLS Downloader!**
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}